Adding MailChimpConnectorProfile
cdklabs/cdk-appflow pull request #154
Opened 2024-03-20 09:19 UTC by remitache

Fixes # This PR adds the MailChimp connector profile using api_key connection.

2024-03-21 09:34 UTC, psrebniak requested changes
Thanks for raising the PR. 
Few minor comments, plus we need to ensure unit test coverage - could you please add one as well? You can use SalesForce tests as a good starting point

2024-03-21 09:34 UTC, psrebniak commented on src/mailchimp/profile.ts
> +    readonly apiKey: string;
apiKey should be passed as a `SecretValue`

2024-03-21 09:34 UTC, psrebniak commented on src/mailchimp/source.ts
> + * A class that represents a Google Analytics v4 Source
* A class that represents a MailChimp v3 Source

2024-03-26 16:37 UTC, psrebniak commented
@remitache please take a look on PR I created to your branch - fixed few problems with profile etc https://github.com/remitache/cdk-appflow/pull/1

2024-03-27 12:50 UTC, psrebniak commented
@remitache thanks for your contribution, really appreciate.

@rpawlaszek @kozub please double check and approve

2024-03-27 12:53 UTC, rpawlaszek approved these changes
LGTM

2024-03-27 12:55 UTC, psrebniak commented
Related issue: #152

2024-03-27 13:13 UTC, merged