Release of Google Ads AppFlow connector
cdklabs/cdk-appflow pull request #200
Opened 2024-05-06 21:11 UTC by remitache

Fixes #

2024-05-07 07:22 UTC, psrebniak commented
Thanks @remitache for raising the PR, appreciate your contribution

Few adjustments required:
- run `npm run projen` to regenerate autogenerated files and run linter on the code, most probably if you fix errors here, next point will not be valid anymore
- tests are failing - please take a look: https://github.com/cdklabs/cdk-appflow/actions/runs/8975852042/job/24651396941?pr=200
- PR has to be linked with issue

Tomorrow I'll add integration test and test it using real connection.

2024-05-08 10:05 UTC, psrebniak requested changes
Two adjustments needed, build is failing due to invalid imports / eslint / tests. 
Once this is solved and PR is attached to issue, we can merge it - really good piece of code!

2024-05-08 10:05 UTC, psrebniak commented on src/googleads/profile.ts
> +          customConnector: {
`customConnector` should also contain following property: 
```
            profileProperties: {
              developerToken: properties.developerToken.unsafeUnwrap(),
              apiVersion: properties.apiVersion,
              managerID: properties.managerID?.unsafeUnwrap() as any /* can be undefined */,
            },
```

2024-05-08 10:05 UTC, psrebniak commented on src/googleads/index.ts
> +/*
need to fix linter - please run `npm run projen` and fix errors once you address remaining comments

2024-05-08 10:05 UTC, psrebniak commented on test/googleads/source.test.ts
> +        ConnectorProfileProperties: {
should have few more props here - please check my previous comments

2024-05-19 21:05 UTC, psrebniak commented
@remitache build still failing - are you sure you added every file to commit? Seems like some of autogenerated files were not added

2024-05-23 11:49 UTC, remitache commented
@psrebniak Yes I pushed all the file but merging still fail. I am not sure why

2024-05-23 14:30 UTC, psrebniak commented
Can you please make sure you're in root directory of project and run 
```sh
yarn run projen
git add .
git commit -m 'autogenerated files'
git push
```
? 
I tried it now and see two files generated. 
If this does not work, then I'll raise PR against your branch to fix CI

2024-05-23 14:39 UTC, psrebniak commented
@remitache ok, apparently `yarn run projen` is not enough, can you do the same with `yarn run build` please?

2024-05-23 15:37 UTC, psrebniak commented
@remitache now it works, one last step required: please create an issue and link your PR for visibility, tomorrow I'll do last check and will merge it. 
Really good work!

2024-05-23 16:02 UTC, remitache commented
@psrebniak I am not able to link an issue with the PR. Just created an empty issue for now.

2024-05-24 07:14 UTC, psrebniak approved these changes
looks good, thanks for your contribution @remitache

2024-05-24 07:14 UTC, merged